### PR TITLE
Adding signup option to the CLI auhtentication options

### PR DESCRIPTION
**Pull request by diaabadr**

### CODE REVIEW

**Comment by Creatoon** [comment]
Add tests : 

- ```Successfull Signup```
- ```Failing Signup```
    - ```Already used email```
    - ```Already used Alias```

Also if you feel to add some more related to your pr then it will be good.

**Comment by diaabadr** [comment]
I don't know why the test cases failed on the pipeline.
https://github.com/metacall/deploy/actions/runs/4440628378/jobs/7810820749
Can you help me with this?

**Comment by diaabadr** [comment]
> Your PR looks awesome, I will do a detailed review after some time, till then please go ahead with the below tasks.
> 
> Add tests :
> 
> * `Successfull Signup`
> * `Failing Signup`
>   
>   * `Already used email`
>   * `Already used Alias`
> 
> Also if you feel to add some more related to your pr then it will be good.

> I have added 4 tests:
> * `Successfull Signup`
> * `Failing Signup`
>   
>   * `Already used email`
> * `Invalid email`
>   * `Already used Alias`
> 
 and they passed:
 
Screenshot from 2023-03-17 19-04-30

> but there are some old test cases fails and I don't know why. Can you check them?

**Comment by Creatoon** [comment]
@diaabadr Yea seems old test case is failing, I am Looking into it.

**Comment by diaabadr** [comment]
@Creatoon Ok. Let me know if there is something I can help with or should I do.

**Comment by diaabadr** [comment]
@Creatoon Can you publish this version so i can use it on the vs code extension

**Comment by Creatoon** [comment]
@diaabadr can i do it tomorrow after some changes?

**Comment by diaabadr** [comment]
@Creatoon No problem.

**Pull request merged**
