### PR TITLE
modified progress api

### PR DESCRIPTION
**Pull request by jatin837**

### CODE REVIEW

**Comment by Siddhant-K-code** [comment]
Hey @jatin837 
First of all, thanks a lot for the PR ✨ 

Can you please add the short description about the changes, it will be easier for you to track the changes with every PR.

**Comment by jatin837** [comment]
zip api requires progress and pulse callback functions.
here's the implementation of zipping the generated package.
original progress api had compilation issue regarding unbound `this`.

**Comment by jatin837** [comment]
I commented the initial Progress interface and the default export.
But, if there's some issue in this implementation, the please let me know.

**Comment by trgwii** [comment]
Can you show the original issue? As far as I can tell this just turns the API into a singleton for no reason.

**Comment by jatin837** [comment]
> Can you show the original issue? As far as I can tell this just turns the API into a singleton for no reason.

while calling the default method, the expected behaviour was to obtain an object which contains two methods, progress & pulse, which will be passed as arguments to zip function. But instead, i was getting [this](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/unbound-method.md) error.
Although, I do agree with your concern here on turning this API into singleton.

I found a better way to resolve this issue, we just need to convert Progress interface methods to arrow function #22.

**Comment by viferga** [comment]
@jatin837 check out my version:
https://github.com/metacall/deploy/commit/397b63bca8a126e626830c26d42e25f35a2264ac

It uses your definition but it is not a singleton.

**Pull request merged**
