### PR TITLE
added test for env variables

### LINKED ISSUE #146: feat: add setupcheck function
We need some enviroment variables while testing and there is a possiblity that dev won't add .env file and running tests without those env vars will be useless.

So this function will check for every enviroment var we need while testing and if succeed then we will run the tests and if not we will simply skip those tests by raising a failure with a message "Env not found or whatever".

### PR DESCRIPTION
**Pull request by GaurKS**
fix #146

### CODE REVIEW

**Comment by viferga** [comment]
@GaurKS @Creatoon I am not sure but maybe we should test this in 'before' rather than in a test.

https://futurestud.io/tutorials/mocha-global-setup-and-teardown-before-after
https://stackoverflow.com/a/39353075

**Comment by viferga** [comment]
Also @Creatoon wait a second until I reset the credentials so we can run the workflow.

**Comment by Creatoon** [comment]
@GaurKS @viferga is right, running the tests before your code will be useless if there are no env vars because eventually the test would fail.
So the thing is, you should test this thing before test start and if there are no env vars, then you must skip the whole test suite by raising an error.

**Comment by viferga** [comment]
@GaurKS check out the code now.

**Pull request merged**
