### PR TITLE
validating-deployments-existence-before-going-in-watch-mode

### PR DESCRIPTION
**Pull request by diaabadr**

### CODE REVIEW

**Comment by diaabadr** [comment]
@Creatoon I have included a new test to evaluate the new validation.

**Comment by viferga** [comment]
Oh shit I did not notice and I have implemented this today XD

I just wanted to inspect through OpenAPIv3 and there was no error info, that's why I added it, then I pushed the changes and I noticed just now that this PR is open.

**Comment by diaabadr** [comment]
No problem. I will 

> By the way, the part of `ensureDeploymentsExist` is still highly useful, can you update this PR with last changes done by me and add this check to inspect?
> 
> I change it to draft meanwhile.

O

**Comment by diaabadr** [comment]
@viferga 
Absolutely, I will update it asap.

**Pull request closed without merging**
